### ISSUE TITLE
Bot offline?

### ISSUE THREAD

**Issue by troygoode** [Ferretsroq/Starforged-Sectors#1]
![image](https://user-images.githubusercontent.com/72844/225103784-714ece8e-7399-4b70-bd0f-34e8748c827c.png)
![image](https://user-images.githubusercontent.com/72844/225103892-0945a980-f653-41f4-ac8d-e5b256c24a25.png)

**Comment by Ferretsroq** [comment]
Bot is back up, thanks!

**Comment by troygoode** [comment]
Thanks for the fast fix!
