### ISSUE TITLE
/sector not working

### ISSUE THREAD

**Issue by troygoode** [Ferretsroq/Starforged-Sectors#2]
Looks likely to be a server error?
![image](https://user-images.githubusercontent.com/72844/225118979-6b545286-229f-44dd-aa98-49eac7b70e34.png)

**Comment by Ferretsroq** [comment]
Can you let me know what your server ID is? Right click the server icon -> copy ID

**Comment by troygoode** [comment]
`1066896587151921152`

**Comment by troygoode** [comment]
FWIW generating planets seems to work fine; it is just the sector command that fails (I've trailed all 4 regions, lowercase & propercase)

**Comment by Ferretsroq** [comment]
It’s very likely this is related to some changes in discordJS that got pushed the other day, I’ll have a look at updating tonight. Thanks!

**Comment by Ferretsroq** [comment]
Fixed with d54b980

**Comment by troygoode** [comment]
Sweet! Verified it works now. Thanks for the quick fix.
